### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by samwilson** [etd-framework/codemirror#1]
Is this package still maintained? There are new versions of CodeMirror.

For anyone else looking at this, it's perhaps better to use a custom repository:
https://github.com/codemirror/CodeMirror/issues/1930#issuecomment-74175553

**Comment by jbanety** [comment]
Hi,

I updated this repo to the latest stable version available.
This is a custom repository used in our projects.

**Comment by samwilson** [comment]
Thanks!
